version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONDODB_DATABASE: api-node
    container_name: api_Node
    volumes:
      - ./mongo:/data/db